import AsyncStorage from '@react-native-async-storage/async-storage';

type Lingua = 'pt' | 'en';

const traducoes: Record<Lingua, Record<string, string>> = {
  pt: {
    app_nome: 'DomésticaMoz',
    app_slogan: 'Emprego doméstico de confiança',
    guardar: 'Guardar',
    cancelar: 'Cancelar',
    seguinte: 'Seguinte',
    anterior: 'Anterior',
    voltar: 'Voltar',
    erro: 'Erro',
    sucesso: 'Sucesso',
    carregando: 'A carregar...',
    sou_trabalhadora: 'Sou Trabalhadora',
    sou_empregador: 'Sou Empregador',
    ja_tenho_conta: 'Já tenho conta?',
    entrar: 'Entrar',
    como_usar: 'Como quer usar a app?',
    trabalhadora_desc: 'Encontre emprego doméstico de confiança',
    empregador_desc: 'Encontre a trabalhadora ideal para si',
    plataforma_segura: 'Plataforma segura e verificada',
    criar_conta: 'Criar conta',
    a_criar_conta: 'A criar conta...',
    preencha_dados: 'Preencha os seus dados',
    preencha_campos: 'Preencha todos os campos obrigatórios',
    nome_completo: 'Nome completo',
    nome_apelido: 'Nome e apelido',
    numero_telemovel: 'Número de telemóvel',
    tipo_documento: 'Tipo de documento',
    documento_identidade: 'Documento de identidade',
    numero_bi: 'Número de BI',
    numero_passaporte: 'Número de passaporte',
    data_nascimento: 'Data de nascimento',
    validade_documento: 'Data de validade do documento',
    nacionalidade: 'Nacionalidade',
    outra: 'Outra',
    bi: 'Bilhete de Identidade (BI)',
    passaporte: 'Passaporte',
    foto_perfil: 'Foto de perfil',
    foto_perfil_desc: 'Tire uma selfie clara do seu rosto',
    foto_bi_frente: 'Foto do BI (frente)',
    foto_bi_verso: 'Foto do BI (verso)',
    foto_passaporte: 'Foto do passaporte',
    selfie_com_documento: 'Selfie com documento',
    selfie_desc: 'Segure o documento perto do rosto e tire uma foto',
    tirar_foto: 'Tirar foto',
    escolher_galeria: 'Escolher da galeria',
    adicionar_foto: 'Adicionar foto',
    como_adicionar_foto: 'Como quer adicionar a foto?',
    adicionar: 'Adicionar',
    editar: 'Editar',
    fotos_documento: 'Fotos do documento',
    fotos_documento_desc: 'As fotos ajudam a verificar a sua identidade.',
    bi_frente: 'BI — frente',
    bi_verso: 'BI — verso',
    passaporte_pagina: 'Passaporte — página principal',
    fotografe_documento: 'Fotografe o documento claramente',
    fotografe_verso: 'Fotografe o verso do BI',
    nota_privacidade_fotos: 'As suas fotos são usadas apenas para verificação de identidade e não são partilhadas publicamente.',
    dados_pessoais: 'Dados pessoais',
    registar_como_trabalhadora: 'A registar como Trabalhadora',
    registar_como_empregador: 'A registar como Empregador',
    ja_tem_conta: 'Já tem conta com este número. Use o botão "Entrar".',
    erro_criar_conta: 'Não foi possível criar a conta.',
    conta_criada: 'Conta criada!',
    conta_criada_desc: 'A sua conta foi criada. Aguarde a verificação pelo administrador.',
    sem_ligacao: 'Sem ligação ao servidor',
    permissao_necessaria: 'Permissão necessária',
    permissao_camara: 'Precisa de permitir o acesso à câmara ou galeria.',
    meus_matches: 'Os meus matches',
    propostas_recebidas: 'Propostas recebidas',
    ver_perfil: 'Ver perfil',
    responder: 'Responder',
    notificacoes: 'Notificações',
    notificacoes_desc: 'As suas notificações aparecerão aqui.',
    sem_notificacoes: 'Sem notificações',
    ver_exemplos: 'Ver exemplos',
    limpar_tudo: 'Limpar tudo',
    definicoes: 'Definições',
    lingua_app: 'Língua da app',
    sobre: 'Sobre',
    conta: 'Conta',
    subscricao_necessaria: 'Subscrição necessária',
    plano_mensal: 'Plano Mensal',
    plano_anual: 'Plano Anual',
    subscrever: 'Subscrever agora',
    acesso_convite: 'Acesso por convite',
    entrar_codigo: 'Entrar com código',
    guardar_perfil: 'Guardar perfil',
    publicar_anuncio: 'Publicar anúncio',
    periodo_teste: 'do período de teste',
    introducir_codigo: 'Introduza o seu código de convite',
    codigo_convite: 'Código de convite',
    codigo_placeholder: 'Ex: MOZDOM2026',
    nao_tem_codigo: 'Não tem código? Partilhe a app com amigos e peça-lhes que lhe enviem o seu código de convite.',
    introduza_numero: 'Introduza o seu número de telemóvel',
    receber_codigo: 'Receber código SMS',
    introducir_numero: 'Introduza o seu número e código de convite',
    matches: 'Matches',
    matches_desc: 'Trabalhadoras compatíveis com o seu anúncio',
    procurar_matches: 'Procurar novas matches',
    sem_matches: 'Ainda não há matches.',
    sem_matches_desc: 'Clique em "Procurar novas matches" para começar.',
    contactar: 'Contactar',
    recusar: 'Recusar',
    compatibilidade: 'Compatibilidade',
    sem_avaliacoes: 'Sem avaliações',
    anos_exp: 'anos exp.',
    a_negociar: 'A negociar',
    mensagens: 'Mensagens',
    sem_conversas: 'Ainda não tem conversas.',
    sem_conversas_desc: 'Contacte uma trabalhadora nos Matches!',
    sem_mensagens_chat: 'Ainda não há mensagens. Diga olá! 👋',
    escreva_mensagem: 'Escreva uma mensagem...',
    contrato: 'Contrato',
    utilizador: 'Utilizador',
    terminar_sessao: 'Terminar sessão',
    terminar_sessao_confirmacao: 'Tem a certeza que quer sair da sua conta?',
    sair: 'Sair',
    limpar_dados: 'Limpar dados locais',
    limpar_dados_confirmacao: 'Tem a certeza que quer limpar todos os dados locais?',
    dados_limpos: 'Dados limpos. Reinicie a app.',
    lingua_alterada: 'Língua alterada',
    lingua_alterada_desc: 'A app está agora em Português. Navegue para outro ecrã para ver as mudanças.',
    versao: 'Versão 1.0.0 — Fase de teste',
    descricao_app: 'Plataforma de emprego doméstico de confiança em Moçambique.',
    nota_fase_testes: 'Durante a fase de testes, use o código de convite que recebeu em vez de SMS.',
    introduza_codigo: 'Introduza um código de convite',
    codigo_valido: 'Código válido!',
    bem_vindo: 'Bem-vindo à DomésticaMoz! Pode criar a sua conta.',
    codigo_invalido: 'Código inválido',
    codigo_invalido_desc: 'Este código de convite não existe ou já foi usado. Peça um código a um amigo ou aguarde o lançamento oficial.',
    acesso_convite_desc: 'A DomésticaMoz está em fase de teste. Para aceder precisa de um código de convite.',
    lingua_padrao: 'Língua padrão',
    lingua_expats: 'Para expatriados e estrangeiros',
  },
  en: {
    app_nome: 'DomésticaMoz',
    app_slogan: 'Trusted domestic employment',
    guardar: 'Save',
    cancelar: 'Cancel',
    seguinte: 'Next',
    anterior: 'Previous',
    voltar: 'Back',
    erro: 'Error',
    sucesso: 'Success',
    carregando: 'Loading...',
    sou_trabalhadora: 'I am a Worker',
    sou_empregador: 'I am an Employer',
    ja_tenho_conta: 'Already have an account?',
    entrar: 'Sign in',
    como_usar: 'How do you want to use the app?',
    trabalhadora_desc: 'Find trusted domestic employment',
    empregador_desc: 'Find the ideal worker for you',
    plataforma_segura: 'Safe and verified platform',
    criar_conta: 'Create account',
    a_criar_conta: 'Creating account...',
    preencha_dados: 'Fill in your details',
    preencha_campos: 'Please fill in all required fields',
    nome_completo: 'Full name',
    nome_apelido: 'First and last name',
    numero_telemovel: 'Phone number',
    tipo_documento: 'Document type',
    documento_identidade: 'Identity document',
    numero_bi: 'ID number',
    numero_passaporte: 'Passport number',
    data_nascimento: 'Date of birth',
    validade_documento: 'Document expiry date',
    nacionalidade: 'Nationality',
    outra: 'Other',
    bi: 'Identity Card (BI)',
    passaporte: 'Passport',
    foto_perfil: 'Profile photo',
    foto_perfil_desc: 'Take a clear selfie of your face',
    foto_bi_frente: 'ID card photo (front)',
    foto_bi_verso: 'ID card photo (back)',
    foto_passaporte: 'Passport photo',
    selfie_com_documento: 'Selfie with document',
    selfie_desc: 'Hold the document near your face and take a photo',
    tirar_foto: 'Take photo',
    escolher_galeria: 'Choose from gallery',
    adicionar_foto: 'Add photo',
    como_adicionar_foto: 'How do you want to add the photo?',
    adicionar: 'Add',
    editar: 'Edit',
    fotos_documento: 'Document photos',
    fotos_documento_desc: 'Photos help verify your identity.',
    bi_frente: 'ID — front',
    bi_verso: 'ID — back',
    passaporte_pagina: 'Passport — main page',
    fotografe_documento: 'Photograph the document clearly',
    fotografe_verso: 'Photograph the back of the ID',
    nota_privacidade_fotos: 'Your photos are used only for identity verification and are not shared publicly.',
    dados_pessoais: 'Personal details',
    registar_como_trabalhadora: 'Registering as a Worker',
    registar_como_empregador: 'Registering as an Employer',
    ja_tem_conta: 'You already have an account with this number. Use the "Sign in" button.',
    erro_criar_conta: 'Could not create the account.',
    conta_criada: 'Account created!',
    conta_criada_desc: 'Your account has been created. Please wait for administrator verification.',
    sem_ligacao: 'No server connection',
    permissao_necessaria: 'Permission required',
    permissao_camara: 'You need to allow access to the camera or gallery.',
    meus_matches: 'My matches',
    propostas_recebidas: 'Received proposals',
    ver_perfil: 'View profile',
    responder: 'Reply',
    notificacoes: 'Notifications',
    notificacoes_desc: 'Your notifications will appear here.',
    sem_notificacoes: 'No notifications',
    ver_exemplos: 'See examples',
    limpar_tudo: 'Clear all',
    definicoes: 'Settings',
    lingua_app: 'App language',
    sobre: 'About',
    conta: 'Account',
    subscricao_necessaria: 'Subscription required',
    plano_mensal: 'Monthly Plan',
    plano_anual: 'Annual Plan',
    subscrever: 'Subscribe now',
    acesso_convite: 'Invite access',
    entrar_codigo: 'Enter with code',
    guardar_perfil: 'Save profile',
    publicar_anuncio: 'Publish ad',
    periodo_teste: 'of the trial period',
    introducir_codigo: 'Enter your invite code',
    codigo_convite: 'Invite code',
    codigo_placeholder: 'E.g.: MOZDOM2026',
    nao_tem_codigo: 'No code? Share the app with friends and ask them to send you their invite code.',
    introduza_numero: 'Enter your phone number',
    receber_codigo: 'Receive SMS code',
    introducir_numero: 'Enter your number and invite code',
    matches: 'Matches',
    matches_desc: 'Workers compatible with your listing',
    procurar_matches: 'Search for new matches',
    sem_matches: 'No matches yet.',
    sem_matches_desc: 'Click "Search for new matches" to start.',
    contactar: 'Contact',
    recusar: 'Decline',
    compatibilidade: 'Compatibility',
    sem_avaliacoes: 'No reviews',
    anos_exp: 'years exp.',
    a_negociar: 'Negotiable',
    mensagens: 'Messages',
    sem_conversas: 'No conversations yet.',
    sem_conversas_desc: 'Contact a worker in Matches!',
    sem_mensagens_chat: 'No messages yet. Say hello! 👋',
    escreva_mensagem: 'Write a message...',
    contrato: 'Contract',
    utilizador: 'User',
    terminar_sessao: 'Sign out',
    terminar_sessao_confirmacao: 'Are you sure you want to sign out?',
    sair: 'Sign out',
    limpar_dados: 'Clear local data',
    limpar_dados_confirmacao: 'Are you sure you want to clear all local data?',
    dados_limpos: 'Data cleared. Restart the app.',
    lingua_alterada: 'Language changed',
    lingua_alterada_desc: 'The app is now in English. Navigate to another screen to see the changes.',
    versao: 'Version 1.0.0 — Trial phase',
    descricao_app: 'Trusted domestic employment platform in Mozambique.',
    nota_fase_testes: 'During the testing phase, use the invite code you received instead of SMS.',
    introduza_codigo: 'Enter an invite code',
    codigo_valido: 'Valid code!',
    bem_vindo: 'Welcome to DomésticaMoz! You can create your account.',
    codigo_invalido: 'Invalid code',
    codigo_invalido_desc: 'This invite code does not exist or has already been used. Ask a friend for a code or wait for the official launch.',
    acesso_convite_desc: 'DomésticaMoz is in test phase. To access you need an invite code.',
    lingua_padrao: 'Default language',
    lingua_expats: 'For expats and foreigners',
  },
};

let linguaActual: Lingua = 'pt';

export const setLingua = async (lingua: Lingua) => {
  linguaActual = lingua;
  await AsyncStorage.setItem('lingua', lingua);
};

export const getLingua = async (): Promise<Lingua> => {
  const lingua = await AsyncStorage.getItem('lingua');
  if (lingua === 'pt' || lingua === 'en') {
    linguaActual = lingua;
    return lingua;
  }
  return 'pt';
};

export const t = (chave: string): string => {
  return traducoes[linguaActual][chave] || chave;
};

export default { t, setLingua, getLingua };